# configuration.nix — top-level system identity and core settings
#
# This file is the entry point for your NixOS config. It is intentionally
# kept lean — it defines who this machine is and handles settings that don't
# belong to any single module. Everything else is split into modules/.
#
# The function arguments here are provided by nixosSystem in flake.nix:
#   config  — the final merged NixOS config (useful for conditionals)
#   pkgs    — the nixpkgs package set for your system
#   inputs  — all flake inputs (passed via specialArgs in flake.nix)
#   ...     — catches any other arguments modules may pass around

{ config, pkgs, inputs, ... }:
{
  # hardware-configuration.nix is auto-generated by the NixOS installer and
  # describes your specific hardware (disks, filesystems, drivers). It lives
  # here rather than in flake.nix because it is tightly coupled to this file.
  imports = [
    ./hardware-configuration.nix
  ];

  # ── System Identity ──────────────────────────────────────────────────────────
  networking.hostName = "FracturedStack";
  time.timeZone       = "America/Phoenix";

  # stateVersion pins the version of NixOS this system was first installed on.
  # It controls defaults for stateful services (databases, file locations) that
  # cannot safely change between releases. Do NOT change this after install —
  # it does not mean you are running an older NixOS, it is just a compatibility
  # marker. Your actual packages come from nixpkgs regardless of this value.
  system.stateVersion = "25.11";

  # ── Nix Settings ────────────────────────────────────────────────────────────
  # Flakes and the `nix` CLI are not enabled by default yet (still experimental
  # upstream). This line opts in to both. You need flakes for this config to
  # work since the whole setup is driven by flake.nix.
  nix.settings.experimental-features = [ "nix-command" "flakes" ];

  # Nix keeps every previous system generation on disk so you can roll back.
  # Without garbage collection this grows indefinitely. This runs weekly and
  # deletes generations older than 7 days, keeping your last ~week of builds.
  nix.gc = {
    automatic = true;
    dates     = "weekly";
    options   = "--delete-older-than 7d";
  };

  # ── Locale ──────────────────────────────────────────────────────────────────
  # defaultLocale sets the system language. extraLocaleSettings fine-tunes
  # locale categories individually (date format, currency, addresses, etc).
  # All set to en_US.UTF-8 here for consistency.
  i18n.defaultLocale = "en_US.UTF-8";

  i18n.extraLocaleSettings = {
    LC_ADDRESS        = "en_US.UTF-8";
    LC_IDENTIFICATION = "en_US.UTF-8";
    LC_MEASUREMENT    = "en_US.UTF-8";
    LC_MONETARY       = "en_US.UTF-8";
    LC_NAME           = "en_US.UTF-8";
    LC_NUMERIC        = "en_US.UTF-8";
    LC_PAPER          = "en_US.UTF-8";
    LC_TELEPHONE      = "en_US.UTF-8";
    LC_TIME           = "en_US.UTF-8";
  };

  # ── Networking ──────────────────────────────────────────────────────────────
  # NetworkManager handles Wi-Fi and wired connections. It is what backs the
  # nm-applet tray icon and nmcli/nmtui CLI tools.
  networking.networkmanager.enable = true;

  # ── Shell ───────────────────────────────────────────────────────────────────
  # Enabling fish at the system level installs it and makes it available as a
  # login shell. The user's shell is set to fish below in users.users.ethan.
  programs.fish.enable = true;

  # ── User Account ────────────────────────────────────────────────────────────
  # Declaratively defines the ethan user. Password is managed separately with
  # `passwd` and is NOT stored here. extraGroups grants:
  #   networkmanager — allows managing network connections without sudo
  #   wheel          — allows sudo / elevated privileges
  users.users.ethan = {
    isNormalUser = true;
    description  = "Ethan Marshall";
    extraGroups  = [ "networkmanager" "wheel" ];
    shell        = pkgs.fish;
    # Per-user packages are better managed through home-manager below.
    # This list is left empty intentionally.
    packages     = with pkgs; [];
  };

  # ── Git ─────────────────────────────────────────────────────────────────────
  # Sets global git config at the system level. This writes to /etc/gitconfig.
  # The email here is a GitHub no-reply address for commit privacy.
  programs.git = {
    enable = true;
    config = [
      {
        user = {
          name  = "Ethan Marshall";
          email = "113003659+Ethan-Marshall@users.noreply.github.com";
        };
        init = {
          defaultBranch = "main";
        };
      }
    ];
  };

  # ── Home Manager ────────────────────────────────────────────────────────────
  # Home Manager manages per-user config declaratively, similar to how NixOS
  # manages the system. home-manager.users.ethan defines ethan's user env.
  # Other modules (e.g. spicetify.nix) also add to this same attribute set —
  # NixOS merges all home-manager.users.ethan blocks across modules together.
  #
  # home.packages here is for user-specific tools that don't need to be
  # system-wide. Prefer this over environment.systemPackages for personal tools.
  home-manager.users.ethan = { pkgs, ... }: {
    nixpkgs.config.allowUnfree = true;
    home.packages = with pkgs; [
      # add user-scoped packages here
    ];
    # Same note as system.stateVersion above — don't change after initial setup.
    home.stateVersion = "25.11";
  };

  # ── Unfree Packages ─────────────────────────────────────────────────────────
  # Nixpkgs marks some packages as "unfree" (proprietary licenses). NixOS
  # blocks them by default as a licensing safeguard. This opts in system-wide.
  # The equivalent line in home-manager.users.ethan above covers HM packages.
  nixpkgs.config.allowUnfree = true;

  # ── Supporting Services ─────────────────────────────────────────────────────

  # Tumbler is a thumbnail generation daemon. Nemo uses it to render image
  # and video previews in the file manager sidebar and icon view.
  services.tumbler.enable = true;

  # GVFS (GLib Virtual File System) gives Nemo access to virtual locations:
  # Trash, MTP devices, network shares, and remote filesystems.
  services.gvfs.enable = true;

  # These three are required by the Noctalia bar to display bluetooth status,
  # battery/power profile info, and UPower device data in its widgets.
  hardware.bluetooth.enable          = true;
  services.power-profiles-daemon.enable = true;
  services.upower.enable             = true;

  # powerManagement enables kernel power management features (cpufreq scaling).
  # acpid listens for ACPI events like lid close, power button, battery alerts.
  powerManagement.enable = true;
  services.acpid.enable  = true;

  # Tighten systemd stop timeouts and disable the watchdog timers.
  # DefaultTimeoutStopSec = "10s" means systemd will wait 10 seconds for a
  # service to stop cleanly before force-killing it (default is 90s).
  # Setting the watchdog values to "0" disables hardware watchdog reboots,
  # which can cause unexpected resets on some laptops.
  systemd.settings.Manager = {
    DefaultTimeoutStopSec = "10s";
    RuntimeWatchdogSec    = "0";
    RebootWatchdogSec     = "0";
  };
}
